default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: ankita
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: mydb

test:
  <<: *default
  database: mydb

production:
  <<: *default
  database: mydb
